# Generated by Django 4.2.2 on 2024-06-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("content", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MailingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало рассылки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец рассылки"
                    ),
                ),
                (
                    "sending",
                    models.CharField(
                        choices=[
                            ("Daily", "Раз в день"),
                            ("Weekly", "Раз в неделю"),
                            ("Monthly", "раз в месяц"),
                        ],
                        max_length=50,
                        verbose_name="Период рассылки",
                    ),
                ),
                (
                    "setting_status",
                    models.CharField(
                        choices=[
                            ("Create", "Создана"),
                            ("Started", "Запущена"),
                            ("Done", "Завершена"),
                        ],
                        default="Create",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailingmessage",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="client.client", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время последней рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Success", "Успешно"), ("Fail", "Не успешно")],
                        default="",
                        max_length=50,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mailing_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="Клиент рассылки",
                    ),
                ),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailingsettings",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус отправки",
                "verbose_name_plural": "Статусы отправки",
            },
        ),
    ]
