# Generated by Django 4.2.2 on 2024-06-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailingsettings",
            old_name="recipients",
            new_name="clients",
        ),
    ]
