# Generated by Django 4.2.2 on 2024-06-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_rename_mailing_list_mailingstatus_mailing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingsettings",
            options={
                "permissions": [
                    ("can_change_setting_status", "Может отключать рассылку")
                ],
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
    ]
