# Generated by Django 4.2.2 on 2024-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingmessage_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="next_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Следующая дата отправки"
            ),
        ),
    ]
