# Generated by Django 4.2.2 on 2024-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Количество просмотров"
            ),
        ),
    ]
