# Generated by Django 4.2.2 on 2024-06-13 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_alter_blogpost_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [
                    ("can_cancel_puplication", "Может отменять публикацию")
                ],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создан пользователем",
            ),
        ),
    ]
