# Generated by Django 4.2.2 on 2024-06-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_options_blogpost_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
    ]
